# Generated by Django 4.2 on 2023-12-08 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('No', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +XXX-XXX-XXXX.', regex='^\\+\\d{1,3}\\d{3}-\\d{3}-\\d{4}$')])),
                ('open_time', models.DateTimeField(auto_now_add=True)),
                ('close_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
